# Please, rename this file to config.yml

# Log filename (default to stdout)
#log-filename: bgpalerter.log
# Log-level (default to INFO)
#log-level: debug

# Proxy host and port (for both websocket and slack)
#proxy-host: proxy.example.com
#proxy-port: 8888

# The streaming service used to have real-time bgp data
websocket-data-service: wss://ris-live.ripe.net/v1/ws/

# The slack integration
slack-web-hook: https://hooks.slack.com/services/XXXX/XXXXXX

sender-notifications-email: me@test.net

notified-emails:
    - email1@test.net
    - email2@test.net

# The file containing the monitored prefixes. Please see monitored_prefixes_test.yml for an example
# This is an array (use new lines and dashes!)
monitored-prefixes-files:
    - monitored_prefixes.base.yml

# After how many announcements from different peers we trigger an alter?
number-peers-before-hijack-alert: 1

# After how many withdrawals from different peers we trigger an alter?
number-peers-before-low-visibility-alert: 5

# 10 seconds is the default
repeat-alert-after-seconds: 10

# 0 for never
repeat-status-heartbeat-after-seconds: 400


# stop sending the same alert after x seconds. Default 600
reset-after-seconds: 60

# permit as65000 to announce subnet of 84.205.65.0/25
#permitted-more-specific-announcements:
#  65000:
#    - 84.205.65.0/26
#    - 84.205.65.64/26
